services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - network

  ollama:
    image: ollama/ollama:latest
    restart: always
    container_name: ollama
    ports:
      - 11434:11434
    environment:
      - MODEL=embed
    networks:
      - network

networks:
  network:
    driver: bridge
